const AiAnalysisPanel = ({ analysis, onAnalyze, loading }) => {
  return (
    <section className="panel ai-panel">
      <div className="panel-header">
        <div>
          <h3>AI Analysis</h3>
          <p>Priority, department, summary, and response generated by AI.</p>
        </div>
        <button type="button" className="secondary-btn" onClick={onAnalyze}>
          {loading ? 'Analyzing...' : 'Run AI analysis'}
        </button>
      </div>
      {analysis ? (
        <div className="ai-grid">
          <div>
            <p className="ai-label">Priority</p>
            <p className="ai-value">{analysis.priority}</p>
          </div>
          <div>
            <p className="ai-label">Department</p>
            <p className="ai-value">{analysis.department}</p>
          </div>
          <div>
            <p className="ai-label">Summary</p>
            <p className="ai-value">{analysis.summary}</p>
          </div>
          <div>
            <p className="ai-label">Auto Response</p>
            <p className="ai-value">{analysis.response}</p>
          </div>
        </div>
      ) : (
        <p className="empty">Run analysis to generate priority and routing details.</p>
      )}
    </section>
  )
}

export default AiAnalysisPanel
